#pragma once

#define GUEST_RUNTIME_STUBS(X)                                                                               \
	X(rv32_ill)                                                                                          \
	X(rv32_fence)                                                                                        \
	X(rv32_fencei)                                                                                       \
	X(rv32_ecall)                                                                                        \
	X(rv32_ebreak)                                                                                       \
	X(rv32_lrw)                                                                                          \
	X(rv32_scw)                                                                                          \
	X(rv32_amoswapw)                                                                                     \
	X(rv32_amoaddw)                                                                                      \
	X(rv32_amoxorw)                                                                                      \
	X(rv32_amoandw)                                                                                      \
	X(rv32_amoorw)                                                                                       \
	X(rv32_amominw)                                                                                      \
	X(rv32_amomaxw)                                                                                      \
	X(rv32_amominuw)                                                                                     \
	X(rv32_amomaxuw)                                                                                     \
	X(rv32_mul)                                                                                          \
	X(rv32_mulh)                                                                                         \
	X(rv32_mulhsu)                                                                                       \
	X(rv32_mulhu)                                                                                        \
	X(rv32_div)                                                                                          \
	X(rv32_divu)                                                                                         \
	X(rv32_rem)                                                                                          \
	X(rv32_remu)                                                                                         \
	X(rv32_csrrw)                                                                                        \
	X(rv32_csrrs)                                                                                        \
	X(rv32_csrrc)                                                                                        \
	X(rv32_csrrwi)                                                                                       \
	X(rv32_csrrsi)                                                                                       \
	X(rv32_csrrci)                                                                                       \
	X(rv32_flw)                                                                                          \
	X(rv32_fld)                                                                                          \
	X(rv32_fsw)                                                                                          \
	X(rv32_fsd)                                                                                          \
	X(rv32_fpop)                                                                                         \
	X(rv32_fmadd)                                                                                        \
	X(rv32_fmsub)                                                                                        \
	X(rv32_fnmsub)                                                                                       \
	X(rv32_fnmadd)                                                                                       \
	X(rv32_mret)                                                                                         \
	X(rv32_vsetvli)                                                                                      \
	X(rv32_vsetvl)                                                                                       \
	X(rv32_vle)                                                                                          \
	X(rv32_vse)                                                                                          \
	X(rv32_vlse)                                                                                         \
	X(rv32_vleff)                                                                                        \
	X(rv32_vsse)                                                                                        \
	X(rv32_vlxei)                                                                               \
	X(rv32_vsxei)                                                                               \
	X(rv32_vlseg)                                                                               \
	X(rv32_vsseg)                                                                               \
	X(rv32_vadd_vv)                                                                                      \
	X(rv32_vsetivli)                                                                                     \
	X(rv32_vialu)                                                                                        \
	X(rv32_vicmp)                                                                                        \
	X(rv32_vmlogic)                                                                                      \
	X(rv32_vmerge)                                                                                       \
	X(rv32_vid)                                                                                          \
	X(rv32_vext)                                                                                \
	X(rv32_vslide)                                                                              \
	X(rv32_vrgather)                                                                            \
	X(rv32_vsatadd)                                                                             \
	X(rv32_vavg)                                                                                \
	X(rv32_vnshift)                                                                             \
	X(rv32_vadc)                                                                                \
	X(rv32_vsmul)                                                                               \
	X(rv32_vlm)                                                                                 \
	X(rv32_vsm)                                                                                 \
	X(rv32_vfwarith)                                                                            \
	X(rv32_vfwred)                                                                              \
	X(rv32_vsshift)                                                                             \
	X(rv32_vnclip)                                                                              \
	X(rv32_vwred)                                                                               \
	X(rv32_vmaskpop)                                                                            \
	X(rv32_vmunary)                                                                             \
	X(rv32_vcompress)                                                                           \
	X(rv32_vwint)                                                                                        \
	X(rv32_vimul)                                                                                        \
	X(rv32_vred)                                                                                         \
	X(rv32_vfalu)                                                                                        \
	X(rv32_vfma)                                                                                         \
	X(rv32_vfcmp)                                                                                        \
	X(rv32_vfcvt)                                                                                        \
	X(rv32_vfunary1)                                                                                     \
	X(rv32_vfred)                                                                                        \
	X(rv32_vfmerge)                                                                                      \
	X(rv32_vfmvfs)                                                                                       \
	X(rv32_vfmvsf)                                                                                         \
	X(rv32_vmvsx)                                                                                        \
	X(rv32_vmvxs)                                                                                          \
	X(rv32_vmvNr)                                                                                        \
	X(rv32_vlNre)                                                                                        \
	X(rv32_vsNr)                                                                                         \
